import { PLStatusBadge } from "~/components/common/status-badge"
import { Colors } from "~/types/base.types"
import { useState } from "react"
import { Sprint, mockSprints } from "~/backend/mocks/sprints"
import { PLIconButton } from "~/components/buttons/icon-button"
import { Outlet, useLocation } from "@remix-run/react"


export default function SprintPage() {
  const [sprints, setSprints] = useState<Array<Sprint>>(mockSprints)
  const {pathname} = useLocation()
  const parsedPath = pathname.split('/sprints/')
  const generationPage = parsedPath.length > 1 && parsedPath[1] === 'generation'

  if (generationPage) {
    return (
      <div>
        <Outlet />
      </div>
    )
  }
  return (
    <div className="w-full flex flex-col">
      <div className="flex items-center justify-between w-full">
        <p className="font-sm italic text-neutral-800 dark:text-neutral-400 mt-5">Review and monitor key details about ProductLamb generated sprints for your project's</p>
        <PLIconButton icon="ri-add-line" />
      </div>
      <div className="mt-5 flex flex-col gap-3">
        {sprints.map((sprint, index) => {
          return <SprintTableRow data={sprint} key={index} repoPlatform={index % 2 === 0 ? 'github' : 'gitlab'}/>
        })}
      </div>
    </div>
  )
}


function SprintTableRow({data, repoPlatform}: {data: Sprint, repoPlatform: 'github' | 'gitlab'}) {
  const [showDetails, setShowDetails] = useState<boolean>(false)

  function toggleDetails() {
    setShowDetails(!showDetails)
  }

  return (
    <div className="w-full p-5 rounded-lg bg-white dark:bg-neutral-800 divide-y-2 flex flex-col gap-5">
      <div className="w-full flex flex-col gap-2">
        <div className="w-full flex flex-row justify-between items-center">
          <h3 className="text-black dark:text-white font-semibold"><span className="text-gray-500">#{data.id}</span> - {data.name}</h3>
          <button className="text-gray-500 dark:text-white font-semibold" onClick={toggleDetails}>
            <i className={showDetails ? 'ri-arrow-up-double-fill' : "ri-arrow-down-double-fill"}></i>
          </button>
        </div>
        <div className="w-full flex justify-start items-center gap-5">
          <p className="italic text-gray-500 dark:text-white"><i className="ri ri-calendar-line"></i> 14 Dec 2022</p>
          <p className="italic text-gray-500 dark:text-white"><i className="ri-task-line"></i> {data.tasks} tasks</p>
          <button>
            <span className="italic text-gray-500 dark:text-white"><i className="ri ri-survey-line"></i> l9879709789-7</span>
          </button>
          <button>
            <span className="text-black dark:text-white">< i className={repoPlatform === 'github' ? "ri-github-fill" : 'ri-gitlab-fill'}></i></span>
          </button>
          <PLStatusBadge color={data.status === 'Completed' ? Colors.GREEN : data.status === 'In Progress' ? Colors.BLUE : data.status === 'Under Construction' ? Colors.YELLOW : Colors.RED} text={data.status}/>
        </div>
      </div>
      <div className={"w-full pt-5 " + (showDetails ? '' : 'hidden')}>
        <p className="text-neutral-700 dark:text-neutral-500"><span className="text-black dark:text-neutral-400 font-semibold">Initiative: </span>This is an example sprint initiative, which is a summary of the higher level goal of a sprint. This dictates what tasks are generated by ProductLamb.</p>
      </div>
    </div>
  )
}